### ISSUE TITLE
can not find automatic labeling method

### ISSUE THREAD

**Issue by sxhmilyoyo** [sheffieldnlp/stance-conditional#18]
In the paper, it said, "the automatic labeling method is publicly available.", but I can not find the automatic labeling code in this repository.
Can you provide the automatic labeling code, please?
Thanks.

**Comment by isabelleaugenstein** [comment]
Apologies, I do not seem to have added this to the commit and now lost the file in the process of moving institutions twice since having worked on the paper. However, if you simply use the set of hashtags/regular expressions as described in the paper, this will suffice, i.e.

> For this purpose we created a small set of regular expressions, based on inspection of the TaskB Unlab corpus, expressing positive and negative stance towards the target. The regular expressions for the positive stance were (Note that “|” indiates “or”, ( ?) indicates optional space): 
• make( ?)america( ?)great( ?)again
• trump( ?)(for|4)( ?)president
• votetrump
• trumpisright
• the truth
• #trumprules
The keyphrases for negative stance were:
#dumptrump, #notrump, #trumpwatch, racist, idiot, fired
A tweet is labelled as positive if one of the positive expressions is detected, else negative if a negative expressions is detected. If neither are detected, the tweet is annotated as neutral randomly with 2% chance.
